version: "3.8"
services:
  # Web server with PHP installed
  www:
    container_name: web
    build:
      dockerfile: Dockerfile7
      context: ./www/.
    depends_on:
      - mysql
    ports:
      - 80:80
    restart: always
    volumes:
      - ../admin/:/var/www/html/admin
      - ./creds.json:/var/www/html/creds.json
    networks:
      - wishit_network
  # Database container    
  mysql:
    container_name: mysql8
    image: mysql:8.0.27
    restart: always
    environment: 
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    ports: 
      - 3306:3306
    networks:
      - wishit_network
    volumes:
      - db_volume:/var/lib/mysql
      - ./db/db.sql:/db.sql
    cap_add:
      - SYS_NICE
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --default-authentication-plugin=mysql_native_password --sql_mode=""
  # PhpMyAdmin
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    depends_on:
      - mysql
      - www
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql8
      - PMA_USER=${MYSQL_USER}
      - PMA_PASSWORD=${MYSQL_PASSWORD}
    networks:
      - wishit_network
# Name the network
networks:
  wishit_network:
# To preserve MySQL data we create a volume
volumes:
  db_volume: